### ISSUE TITLE
Mapping not shown in "Load Preset"

### ISSUE THREAD

**Issue by ph3ne** [dan-giddins/mixxx-ddj-200-mapping#1]
Hello and first thank you for your work on this little controller,

I'm trying to install the preset on Windows 10. I placed the JS and XML files in the "C:\Users\<CurrenUser>\AppData\Local\Mixxx\controllers" folder but the mapping doesn't appear in the "Load Preset" list when I go to "Preferences>Controllers>DDJ-200>Controller Setup" in Mixxx 2.2.3.

How do you properly install the custom MIDI mapping?

Thanks in advance,

**Comment by dan-giddins** [comment]
The mapping should just work if you click on 'DDJ-200' on the list under
'Controllers' on the left. If you go to the 'input mappings', you should
see a list of the many mappings for the input mappings.

**Comment by ph3ne** [comment]
Thank you, it finally worked somehow.

**Comment by dan-giddins** [comment]
No worries! Glad it worked for you :)
Let me know if you come into any problems with the mapping. I have raised a
request for it to be added to MIXXX by default, which will be nice
