### ISSUE TITLE
Ddj200 pioneer

### ISSUE THREAD

**Issue by Vernongov** [dan-giddins/mixxx-ddj-200-mapping#2]
Purchased a ddj20o controller
Downloaded the mixxx app 
There is no load preset for the controller
Please can someone assist

**Comment by dan-giddins** [comment]
A pull request for support for the DDJ-200 has been raised to bring the
functionality into the program by default, but for now you can get the
controller working by downloading the following files into
C:\Users\<user>\AppData\Local\Mixxx\controllers\ (also known as the "User
Preset Folder" in Preferences -> Controllers)
https://raw.githubusercontent.com/dan-giddins/mixxx-ddj-200-mapping/master/DDJ-200.midi.xml
https://raw.githubusercontent.com/dan-giddins/mixxx-ddj-200-mapping/master/Pioneer-DDJ-200-scripts.js
(right-click -> save as)

**Comment by Vernongov** [comment]
Hi
Thank you for the feedback
U will try it
