### ISSUE TITLE
Is it possible to get LEDs working?

### ISSUE THREAD

**Issue by fkbreitl** [dan-giddins/mixxx-ddj-200-mapping#4]
Thanks you very much. It works!

Except I never see LEDs changing their brightness.
Would it be possible to make them change and for example switch on and off?

**Comment by dan-giddins** [comment]
I never got round to implementing this as it wasn't something I particularity felt was important. I'm away from home right now so unfortunately I'm not going to be able to implement this anytime soon. If you are interested in adding this functionality, feel free to fork this repo and improve the mapping! More info can be found here: https://github.com/mixxxdj/mixxx/wiki/Components-JS

If it looks good, I am happy to add it to my mapping PR to get it in MIXXX by default!

**Comment by fkbreitl** [comment]
Thanks for the link. That's very helpful.
I could try adding a few LEDs if you could give me an example snippet for e.g. the play button.
I have already looked at some other Pioneer controller JS but didn't understand it since I am totally new to Mixxx.

Looking at https://github.com/mixxxdj/mixxx/wiki/MIDI%20controller%20mapping%20file%20format I get the impression that switching on and off LEDs could even be achieved via the xml file.

> The <outputs> element defines outputs that use "short" (3-byte) MIDI messages. Use this to control LEDs and other features of your controller to make them react to changes in Mixxx. Within the <outputs> element, put as many <output> elements as necessary. Note that this can only send either of two different values, so it is most useful for LEDs that can only be switched on and off.

What do you think?

**Comment by dan-giddins** [comment]
Ahh yes, that was the page I was looking for but couldn't find... I used that page to do the initial mapping.

Yes it looks like you can do LEDs in XML by the looks of that. I think we should be using XML where possible, but for the Jog wheels I had to use Javascript to interact with MIXXX's more complex scratching engine...

**Comment by fkbreitl** [comment]
I was able to get some LEDs working, most important the BEAT SYNC.
I created a pull request. I hope you can see it.
I couldn't get the hotcues to work yet. For this and blinking LEDs I think I need more help.

**Comment by fkbreitl** [comment]
Could you get my changes via my pull request or would you like me to attach it here?

**Comment by dan-giddins** [comment]
@fkbreitl yes I saw your changes, and I have left a comment on the  pr: #5

**Comment by dan-giddins** [comment]
@fkbreitl sorry, the comment was left 'pending' I forgot to submit it

**Comment by fkbreitl** [comment]
Ah, I see your comment.
What exactly do you want me to do?
Change the comment? To what? Can you give me an example?

**Comment by fkbreitl** [comment]
I also got the hotcue LEDs working thanks to the help of [Mixxx developer hlzhs](https://mixxx.discourse.group/t/how-to-switch-on-hotcue-leds/19997/2?u=aldous).
You should be able to merge it from my pull request.
