### ISSUE TITLE
Jog wheel not aligning to beatgrid of other track

### ISSUE THREAD

**Issue by fkbreitl** [dan-giddins/mixxx-ddj-200-mapping#7]
Hi Dan,

I think there is another issue with the jog wheel not aligning to the beatgrid of the other track.
I have asked this at the user forum

https://mixxx.discourse.group/t/jog-wheel-not-snapping-to-beatgrid/20044

but did not get a response yet.
I am not sure if this is just a problem of the DDJ-200 mapping or if it is general to all controllers.
So I have also reported it as a bug just in case but also didn't get a response yet:

https://bugs.launchpad.net/mixxx/+bug/1898701

Do you have another controller to test if it behaves differently?

Cheers

Frank

**Comment by dan-giddins** [comment]
I can't test this at the moment, sorry!

**Comment by dan-giddins** [comment]
I will be able to test this when I am next at home though

**Comment by fkbreitl** [comment]
Meanwhile my bug report has been confirmed.
So it is not a problem of our mapping.
So we can close this issue here.
